Fix Readme with local setup and other relevant information
fylein/fyle-xero-app-2 pull request #1
Opened 2022-08-11 09:19 UTC by DhaaraniCIT

2022-08-12 10:26 UTC, ashwin1111 commented on src/index.html
> +  <title>Fyle QuickBooks Integration</title>
Fyle Xero Integration

2022-08-12 11:28 UTC, ashwin1111 requested changes

2022-08-12 11:28 UTC, ashwin1111 commented on src/app/app-routing.module.ts
> +// Export class AppRoutingModule { }
Why is this completely commented out? why not just make the routes []

2022-08-12 11:28 UTC, ashwin1111 commented on src/app/app.component.html
> +<h1>Xero Integration</h1>
Why?

2022-08-12 11:28 UTC, ashwin1111 commented on src/app/app.module.ts
> +// Import { AppRoutingModule } from './app-routing.module';
same

2022-08-16 02:41 UTC, DhaaraniCIT commented on src/app/app.component.html
> +<h1>Xero Integration</h1>
just for a placeholder

2022-08-16 05:51 UTC, ashwin1111 approved these changes

2022-08-16 05:51 UTC, ashwin1111 commented on src/app/app.component.html
> +<h1>Xero Integration</h1>
not needed, please remove, it doesn't add any value

2022-08-16 06:42 UTC, DhaaraniCIT commented on src/app/app.component.html
> +<h1>Xero Integration</h1>
shall i keep it as a blank page

2022-08-16 06:43 UTC, ashwin1111 commented on src/app/app.component.html
> +<h1>Xero Integration</h1>
yes

2022-08-16 06:48 UTC, merged