Shared module commite
fylein/fyle-xero-app-2 pull request #5
Opened 2022-08-23 09:07 UTC by DhaaraniCIT

2022-08-24 09:13 UTC, ashwin1111 requested changes

2022-08-24 09:13 UTC, ashwin1111 commented on src/app/core/services/misc/mapping.service.ts
> +  getAllMappings(sourceType: string, limit: number, uri: string, pageOffset: number, tableDimension: number): Observable<Mapping[]> {
please add only needed methods, these are not needed

2022-08-24 09:13 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/add-email-dialog/add-email-dialog.component.spec.ts
>  describe('AddEmailDialogComponent', () => {
this component is not needed, we don't have support for email notif in Xero

2022-08-24 09:13 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/add-email-dialog/add-email-dialog.component.ts
> +    @Inject(MAT_DIALOG_DATA) public data: AdvancedSettingAddEmailModel
this component is not needed, we don't have support for email notif in Xero

2022-08-24 09:13 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.html
> +      <!-- <app-configuration-toggle-field *ngIf="showAutoCreateVendorsField()" [form]="advancedSettingsForm"
remove commented code

2022-08-25 06:24 UTC, DhaaraniCIT commented on src/app/core/interceptors/jwt.fixture.ts
> -  expires_in: 3600,
the model of token of xero did not have that, so only

2022-08-25 06:46 UTC, ashwin1111 commented on src/app/core/interceptors/jwt.fixture.ts
> -  expires_in: 3600,
need not compare the old code, instead compare with the API response

2022-08-26 13:47 UTC, ashwin1111 commented
Need not request review at this point, I'll go through the commits on our daily call @DhaaraniCIT

2022-08-29 07:35 UTC, ashwin1111 commented on src/app/core/services/workspace/workspace.service.ts
> -  getFyleCurrency(): string {
```currency: {
  xero: 'USD',
  fyle: 'INR'
}

2022-08-29 07:39 UTC, ashwin1111 commented on src/app/shared/components/dashboard/dashboard-export-log-dialog/dashboard-export-log-dialog.component.ts
> -    this.exportLogService.getExpenseGroups(state, 500, 0, null, this.data.lastExportedAt).subscribe((expenseGroupResponse: ExpenseGroupResponse) => {
this component is not needed, remove completely

2022-09-01 07:06 UTC, ashwin1111 commented on src/app/app-routing.module.ts
> +    // CanActivate: [AuthGuard]
keep them in the code, find the reason for error

2022-09-01 07:10 UTC, ashwin1111 commented on src/app/core/services/configuration/xero-connector.service.ts
> +  postTenantMappings(workspaceId: number, tenantName: string, tenantId: string): Observable<TenantMapping> {
for all post endpoint, try maintaining a single object,
example - tenantMappingPayload: TenantMappingPost

tenantMappingPayload = {...}

2022-09-01 07:13 UTC, ashwin1111 commented on src/app/core/services/workspace/workspace.service.ts
> +  getFyleCurrency() {
getCurrency

2022-09-01 07:15 UTC, ashwin1111 commented on src/app/shared/components/configuration/configuration-step-header-section/configuration-step-header-section.component.html
> -        {{ contentText }} <span class="header-section--learn-more-btn pointer" (click)="helperService.openExternalLink(helpArticleLink)">Learn more</span>
add todo

2022-09-01 07:16 UTC, ashwin1111 commented on src/app/shared/components/configuration/xero-connector/xero-connector.component.html
> +                <!-- <img *ngIf="xeroConnectorForm.value.xeroTenant === option.value" src="assets/images/svgs/general/tick-pink.svg" class="selected-value-check-mark"> -->
keep the tick mark

2022-09-01 07:21 UTC, ashwin1111 commented on src/app/shared/components/configuration/xero-connector/xero-connector.component.ts
> +    const xeroTenant = this.tenantList.filter(filteredTenant => filteredTenant.destination_id === tenantId)[0];
follow new way of storing value in select fields

2022-09-01 07:21 UTC, ashwin1111 commented on src/app/shared/components/configuration/xero-connector/xero-connector.component.ts
> +    if (tenantId) {
check form.valid instead of tenant id

2022-09-01 07:25 UTC, ashwin1111 commented on src/app/shared/components/core/header/header.component.ts
> +  currency: any = this.workspaceService.getFyleCurrency();
define a type

2022-09-05 07:33 UTC, ashwin1111 commented on src/app/core/models/configuration/export-setting.model.ts
> +  value: ExpenseState | ReimbursableExpensesObject | CorporateCreditCardExpensesObject | ExpenseGroupingFieldOption | ExportDateType | string;
don't add string, instead use types

2022-09-05 07:34 UTC, ashwin1111 commented on src/app/core/models/db/tenant-mapping.model.ts
> +export type TenantMappingPayload = {
TenantMappingPost

2022-09-05 07:36 UTC, ashwin1111 commented on src/app/core/services/misc/mapping.service.ts
> -    const params: {attribute_types: string | string[], active?: boolean} = {
API is available, need not mock

2022-09-05 07:37 UTC, ashwin1111 commented on src/app/core/services/misc/mapping.service.ts
> +    const response:ExpenseField[]=[
need not mock, use existing API

2022-09-05 07:38 UTC, ashwin1111 commented on src/app/core/services/workspace/workspace.service.ts
> +    // Return this.apiService.post(`/workspaces/${workspaceId}/xero/sync_dimensions/`, {}).pipe(
use existing api, need not mock

2022-09-05 07:38 UTC, ashwin1111 commented on src/app/core/services/workspace/workspace.service.ts
> +    return of({});
use existing api, need not mock

2022-09-05 07:38 UTC, ashwin1111 commented on src/app/core/services/workspace/workspace.service.ts
> +    return of({});
use existing api, need not mock

2022-09-05 07:39 UTC, ashwin1111 commented on src/app/integration/integration.component.ts
> +      this.storageService.set('onboardingState', 'EXPORT');
EXPORT_SETTINGS

2022-09-05 07:40 UTC, ashwin1111 commented on src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
> +    <div *ngIf="note&&options===null&&xeroAttributes===null" class="configuration--form-field">
`exportType` instead of `note`

2022-09-05 07:43 UTC, ashwin1111 commented on src/app/shared/components/configuration/export-settings/export-settings.component.html
>            [formControllerName]="'reimbursableExportType'"
reimbursableExportType is not needed, handle this in construct payload part in model

2022-09-05 07:44 UTC, ashwin1111 commented on src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
> +    <div *ngIf="note&&options===null&&xeroAttributes===null" class="configuration--form-field">
`options===null&&xeroAttributes===null` is not needed

2022-09-05 07:47 UTC, ashwin1111 commented on src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
> +    <mat-form-field *ngIf="placeholder !== null && options !== null || xeroAttributes !== null" floatLabel="always" appearance="outline" class="configuration--form-field">
`*ngIf="!exportType"`

2022-09-05 07:47 UTC, ashwin1111 commented on src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
> +      <p *ngIf="formControllerName === 'reimbursableExportType' && options !== null || xeroAttributes !== null">Click <span class="configuration-select-field--preview-btn pointer" (click)="showXeroEx
!exportType

2022-09-05 07:47 UTC, ashwin1111 commented on src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
> +      <p *ngIf="formControllerName === 'creditCardExportType'  && options !== null || xeroAttributes !== null">Click <span class="configuration-select-field--preview-btn pointer" (click)="showXeroExp
!exportType

2022-09-05 07:48 UTC, ashwin1111 commented on src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
> +    <!-- <div *ngIf="formControllerName === 'autoMapEmployees'" class="configuration-select-field--select-example-section paragraph">
remove comment

2022-09-05 07:49 UTC, ashwin1111 commented on src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.scss
> +  &--note{
` &--note {`
indent

2022-09-05 07:50 UTC, ashwin1111 commented on src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.ts
> +  @Input() note: string
`@Input() exportType: ReimbursableExpensesObject | CorporateCreditCardExpensesObject`

2022-09-05 07:50 UTC, ashwin1111 commented on src/app/shared/components/configuration/configuration-step-header-section/configuration-step-header-section.component.html
> +    <!-- <div class="header-section--sync-btn" *ngIf="showSyncButton && (activePage === 'export_settings' || activePage === 'import_settings' || activePage === 'advanced_settings')">
remove comment

2022-09-05 07:52 UTC, ashwin1111 commented on src/app/shared/components/configuration/export-settings/export-settings.component.html
> +            [mandatoryErrorListName]="'Purhase Bill'"
Purchase* typo

2022-09-05 07:55 UTC, ashwin1111 commented on src/app/shared/components/configuration/export-settings/export-settings.component.html
> +          [options]="creditCardExportTypes"
[xeroAttributes]=bank account list

2022-09-05 07:56 UTC, ashwin1111 commented on src/app/shared/components/configuration/export-settings/export-settings.component.ts
> +      value: AutoMapEmployee.EMPLOYEE_CODE
null

2022-09-05 07:56 UTC, ashwin1111 commented on src/app/shared/components/configuration/export-settings/export-settings.component.ts
> +      value: AutoMapEmployee.EMPLOYEE_CODE
label and value has different meaning

2022-09-05 07:58 UTC, ashwin1111 commented on src/app/shared/components/configuration/export-settings/export-settings.component.ts
> +      label: 'Employee email on Fyle to contact email  on Xero',
`email  on Xero` has double space

2022-09-05 07:58 UTC, ashwin1111 commented on src/app/shared/components/configuration/export-settings/export-settings.component.ts
> +      label: 'Approved',
remove Approved and Verified

2022-09-05 07:58 UTC, ashwin1111 commented on src/app/shared/components/configuration/export-settings/export-settings.component.ts
> +      label: 'Payment processing',
maintain title casing, Payment Processing

2022-09-05 08:04 UTC, ashwin1111 commented on src/app/shared/components/configuration/export-settings/export-settings.component.ts
> -  private paymentsSyncAffected(): boolean {
this is needed, `paymentsSyncAffected`

2022-09-05 08:05 UTC, ashwin1111 commented on src/app/shared/components/configuration/export-settings/export-settings.component.ts
> -    if (!this.singleItemizedJournalEntryAffected() && this.paymentsSyncAffected()) {
this.paymentsSyncAffected() this is needed

2022-09-05 08:06 UTC, ashwin1111 commented on src/app/shared/components/configuration/xero-connector/xero-connector.component.html
> +              <mat-option *ngFor="let option of tenantList" [value]="{id:option.destination_id,name:option.value}">
indent, `{id: option.destination_id, name: option.value}`

2022-09-05 08:07 UTC, ashwin1111 commented on src/app/shared/components/configuration/xero-connector/xero-connector.component.html
> +                <img *ngIf="xeroConnectorForm.value.xeroTenant === option.value" src="assets/images/svgs/general/tick-pink.svg" class="selected-value-check-mark">
convert to json and compare with option.value

2022-09-05 08:10 UTC, ashwin1111 commented on src/app/shared/components/configuration/configuration-toggle-field/configuration-toggle-field.component.html
> +<div *ngIf = "formControllerName === 'chartOfAccount'" class="configuration--field-toggle-section">
`*ngIf="formControllerName === 'chartOfAccount'"`

2022-09-05 08:15 UTC, ashwin1111 commented on src/app/shared/components/configuration/import-settings/import-settings.component.html
> +                  Import specific tracking category {{ i !==0 ? i+1 : '' }}
specific tracking category is not needed

2022-09-05 08:15 UTC, ashwin1111 commented on src/app/shared/components/configuration/import-settings/import-settings.component.html
> +                  Import specific tracking category {{ i !==0 ? i+1 : '' }}
reset to original state

2022-09-05 08:15 UTC, ashwin1111 commented on src/app/shared/components/configuration/import-settings/import-settings.component.html
> -                    The imported {{ expenseField.value.destination_field | titlecase }} from Xero will be a
reset to original state

2022-09-05 08:18 UTC, ashwin1111 commented on src/app/shared/components/configuration/import-settings/import-settings.component.html
> -                        {{ expenseField.value.destination_field | titlecase }} in Xero
reset to original state

2022-09-05 08:20 UTC, ashwin1111 commented on src/app/shared/components/configuration/import-settings/import-settings.component.html
> +                    <mat-form-field floatLabel="always" appearance="outline" class="import-settings--fyle-field">
this is not needed

2022-09-05 08:22 UTC, ashwin1111 commented on src/app/core/services/configuration/xero-connector.service.ts
>      return of(response);
use existing api, need not mock

2022-09-05 08:23 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.scss
> +  &--schedule-dropdown{
`&--schedule-dropdown {`

2022-09-05 08:23 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.scss
> +.configuration--form-field{
`.configuration--form-field {`

2022-09-05 08:24 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.ts
> +      this.workspaceService.getWorkspaceGeneralSettings()
remove not needed functions like `showSingleCreditLineJEField`

2022-09-05 08:25 UTC, ashwin1111 commented on src/app/shared/components/configuration/import-settings/import-settings.component.html
> -                  [disabled]="expenseFields.value.disable_import_to_fyle" formControlName="import_to_fyle">
`formControlName="import_to_fyle"` this is needed, check what is the error

2022-09-06 07:11 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.ts
> -  showPaymentSyncField(): boolean {
this condition is needed

2022-09-06 07:12 UTC, ashwin1111 commented on src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
> +      <b class="configuration-select-field--exportType">{{exportType}}</b>
`export-type` instead of `exportType`

2022-09-06 07:12 UTC, ashwin1111 commented on src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.scss
> +  &--exportType {
export-type

2022-09-06 07:14 UTC, ashwin1111 commented on src/app/shared/components/configuration/export-settings/export-settings.component.ts
> +      // Response[1].BANK_ACCOUNT;
remove commented code

2022-09-06 07:15 UTC, ashwin1111 commented on src/app/shared/components/configuration/export-settings/export-settings.component.ts
> +    return this.exportSettings?.workspace_general_settings?.reimbursable_expenses_object !== ReimbursableExpensesObject.PURCHASE_BILL && this.exportSettingsForm.value.reimbursableExportType  === Reim
double space here this.exportSettingsForm.value.reimbursableExportType  === ReimbursableExpen

2022-09-06 07:16 UTC, ashwin1111 commented on src/app/shared/components/configuration/xero-connector/xero-connector.component.html
> +                <img *ngIf="xeroConnectorForm.value.xeroTenant === option.value" src="assets/images/svgs/general/tick-pink.svg" class="selected-value-check-mark">
fix

2022-09-06 13:14 UTC, merged