custom mapping changes commit
fylein/fyle-xero-app-2 pull request #9
Opened 2022-09-12 09:05 UTC by DhaaraniCIT

2022-09-22 14:14 UTC, ashwin1111 requested changes

2022-09-22 14:14 UTC, ashwin1111 commented on src/app/core/services/misc/mapping.service.ts
> +  postMapping(mapping: MappingPost) {
return type

2022-09-22 14:14 UTC, ashwin1111 commented on src/app/core/services/misc/mapping.service.ts
> +  getXeroField(): Observable<[]> {
`getXeroFields`, return type is incorrect

2022-09-22 14:14 UTC, ashwin1111 commented on src/app/integration/main/mapping/custom-mapping/custom-mapping.component.ts
> +    this.mappingService.getXeroField().subscribe(
`this.mappingService.getXeroField()` this call can be clubbed along with other API calls done in `setupSettingsAndSetupPage()`

The reason is, they can go in parallel and reduce time. Nesting them will cause them to wait. 1st call succeeds and only after that 2nd request would be sent

2022-09-22 14:14 UTC, ashwin1111 commented on src/app/integration/main/mapping/custom-mapping/custom-mapping.component.ts
> +        this.xeroFields = this.xeroFields.filter((xeroField: any) => !this.mappingSettings.includes(xeroField));
replace any with proper relevant type

2022-09-22 14:14 UTC, ashwin1111 commented on src/app/integration/main/mapping/custom-mapping/custom-mapping.component.ts
> +      return (mappingSetting.destination_field !== MappingDestinationField.ACCOUNT && mappingSetting.destination_field !== MappingDestinationField.BANK_ACCOUNT && mappingSetting.destination_field !==
indent is off

2022-09-22 14:14 UTC, ashwin1111 commented on src/app/integration/main/mapping/mapping-routing.module.ts
> -        component: EmployeeMappingComponent
incase if EmployeeMappingComponent is copied, please delete them

2022-09-22 14:14 UTC, ashwin1111 commented on src/app/shared/components/mapping/generic-mapping/generic-mapping.component.ts
> +      this.mappingSetting = mappingSetting.length ? mappingSetting[0] : {source_field: FyleField.CATEGORY, destination_field: FyleField.PROJECT};
`destination_field` should be Xero Account and not Fyle Project

2022-09-22 14:14 UTC, ashwin1111 commented on src/app/shared/components/mapping/mapping-table/mapping-table.component.ts
> +    if (this.sourceType?.toUpperCase() === TenantFieldMapping.TENANT) {
this condition is not required, this is specific to QBO

2022-09-23 05:42 UTC, DhaaraniCIT commented on src/app/core/services/misc/mapping.service.ts
> +  postMapping(mapping: MappingPost) {
what type I should assign for this, in QBO it is employeeMapping, but in xero we don't have that

2022-09-26 04:39 UTC, ashwin1111 commented on src/app/core/services/misc/mapping.service.ts
> +  postMapping(mapping: MappingPost) {
Please check the API response and create a type if it doesn't exist

2022-09-26 04:42 UTC, ashwin1111 approved these changes

2022-09-26 07:53 UTC, merged